<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-MBB97ED5" failures="1" tests="5" name="Default test" time="17.093" errors="0" timestamp="2023-07-03T19:09:58 EDT">
  <testcase classname="com.tutorialsninja.qa.testcases.LoginTest" name="verifyLogInWithValidCredentials" time="0.564">
    <failure type="org.testng.internal.reflect.MethodMatcherException" message="
[public void com.tutorialsninja.qa.testcases.LoginTest.verifyLogInWithValidCredentials(java.lang.String,java.lang.String)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: verifyLogInWithValidCredentials([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) mi76a_98a_1@gmail.com]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void com.tutorialsninja.qa.testcases.LoginTest.verifyLogInWithValidCredentials(java.lang.String,java.lang.String)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: verifyLogInWithValidCredentials([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) mi76a_98a_1@gmail.com]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:43)
at org.testng.internal.Parameters.injectParameters(Parameters.java:914)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:34)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyLogInWithValidCredentials -->
  <testcase classname="com.tutorialsninja.qa.testcases.LoginTest" name="verifyLogInWithInvalidCredentials" time="1.246"/>
  <testcase classname="com.tutorialsninja.qa.testcases.LoginTest" name="verifyLogInWithValidEmailInvalidPassword" time="1.038"/>
  <testcase classname="com.tutorialsninja.qa.testcases.LoginTest" name="verifyLogInWithInvalidEmailValidPassword" time="1.015"/>
  <testcase classname="com.tutorialsninja.qa.testcases.LoginTest" name="verifyLoginWithNoCredentials" time="1.197"/>
</testsuite> <!-- Default test -->
